grocery: grocery.cpp
	g++ -std=c++17 -Wall -o grocery grocery.cpp

timing: set_timing.cpp
	g++ -std=c++17 -Wall -o timing set_timing.cpp

user_registration: user_registration.cpp
	g++ -std=c++17 -Wall -o user_registration user_registration.cpp
