hello: hello_world.cpp

	g++ -std=c++17 -o hello hello_world.cpp

add: add_numbers.cpp
	g++ -std=c++17 -o add add_numbers.cpp

smith: wordsmithing.cpp
	g++ -std=c++17 -o smith wordsmithing.cpp

prod: product.cpp
	g++ -std=c++17 -o prod product.cpp

bigs: bigs.cpp
	g++ -std=c++17 -o bigs bigs.cpp

again: say_that_again_solution.cpp
	g++ -std=c++17 -o again say_that_again_solution.cpp
