framing: const_demo_framing.cpp
	g++ -std=c++17 -Wall -o framing const_demo_framing.cpp 

telling: const_demo_telling.cpp
	g++ -std=c++17 -Wall -o telling const_demo_telling.cpp 

punchline: const_demo_punchline.cpp
	g++ -std=c++17 -Wall -o punchline const_demo_punchline.cpp 

reckless: reckless.cpp
	g++ -std=c++17 -Wall -o reckless reckless.cpp 
	
heavy: heavy_copy.cpp
	g++ -std=c++17 -Wall -o heavy heavy_copy.cpp

super: super_type.cpp
	g++ -std=c++17 -Wall -o super super_type.cpp

swap: swap.cpp
	g++ -std=c++17 -Wall -o swap swap.cpp

