include: include_demo.cpp
	g++ -std=c++17 -Wall -o include include_demo.cpp

macros: macro_demo.cpp
	g++ -std=c++17 -Wall -o macros macro_demo.cpp

macros_debug: macro_demo.cpp
	g++ -std=c++17 -Wall -DDEBUG -o macros_debug macro_demo.cpp

bullets: add_bullets.cpp
	g++ -std=c++17 -Wall -o bullets add_bullets.cpp
