stuff: uses_stuff.cpp stuff.h
	g++ -std=c++17 -Wall -o stuff uses_stuff.cpp


pair_demo: pair_demo.cpp
	g++ -std=c++17 -Wall -o pair_demo pair_demo.cpp


counters: counter_demo.cpp
	g++ -std=c++17 -Wall -o counters counter_demo.cpp


noisy: noisy_vector.h noisy_vector_solution.h noisy_demo.cpp
	g++ -std=c++17 -Wall -o noisy noisy_demo.cpp
