timing: sequential_timing.cpp
	g++ -Wall -std=c++17 -o timing sequential_timing.cpp

sslist: singly_linked.cpp
	g++ -Wall -std=c++17 -o sslist singly_linked.cpp

range: range.cpp
	g++ -Wall -std=c++17 -o range range.cpp
	